name: UI and API

on:
  push:
    branches:
      - "*"

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  API_SERVICE_NAME: complete-word-api
  UI_SERVICE_NAME: complete-word-ui
  REGION: us-east4
  API_IMAGE_NAME: complete-word-api-image
  UI_IMAGE_NAME: complete-word-ui-image

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      ui: ${{ steps.filter.outputs.ui }}
      workflow: ${{ steps.filter.outputs.workflow }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.head_ref }}
          filters: |
            api:
              - 'api/**'
            ui:
              - 'ui/**'
            workflow:
              - '.github/workflows/**'

  api:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true' || needs.detect-changes.outputs.workflow == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: |
            api/

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and Push Docker Image
        run: |
          docker build -t cloud-run-source-deploy/${{ secrets.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:latest .
          docker push cloud-run-source-deploy/${{ secrets.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $API_SERVICE_NAME \
            --image cloud-run-source-deploy/${{ secrets.GCP_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:latest \
            --platform managed \
            --region us-east4 \
            --allow-unauthenticated
